### ISSUE TITLE
missing dependency in synExp.hpp

### ISSUE THREAD

**Issue by h3ssto** [davidfa71/Extending-Logic#3]
Hi, when executing the Makefile in `code` I got some crude compiler messages like `error: 'numeric_limits' is not a member of 'std'` and the make fails. I fixed the issue by adding `#include <limits>` to `code/tools/src/synExp.hpp`

Best regards
Tobias

**Comment by davidfa71** [comment]
Thanks Tobias, I have included it. Regards.

David
